### ISSUE TITLE
Caller ID not transferring on blind transfer using transfer softkey

### ISSUE THREAD

**Issue by rofferman** [marcelloceschia/chan-sccp-b#473] opened 2019-09-09 21:40 UTC
When I transfer a call using the transfer softkey the caller id of the inbound caller is not sent with the call, instead the name of internal extension is sent.
If I use ## to transfer the call is transferred with the caller id information correctly

I am using freepbx with asterisk 16. 

This was working up until a few weeks ago.  I cannot figure out what has changed

**Comment by dkgroot** [comment] 2019-09-09 21:49
@rofferman 
I am not sure which revision might have caused this. Most resent commit merges are only done after quite a bit of testing, to prevent regressions. I am not a 100% sure, what you mean by `internal extension` to be honest. An example (either as image or text) of the shown callinfo would have been more helpfull.

Would you be able to do a `git bisect` to figure out which commit cause the regression. To find the revision you were on previously (a couple of weeks ago) you can use `git reflog`.

**Comment by rofferman** [comment] 2019-09-09 21:58
For example  a call comes in with the caller id of the incoming caller.. The caller is transferred to another phone in the building. The original caller id showing the callee is overwritten by the extension that is transferring the call. So the phone that the call was transferred to is showing the extension of the phone that transferred the call. 

I can get some log information uploaded tomorrow and get the version of the module I am on.
Would the asterisk logs showing this transfer be of help?

**Comment by dkgroot** [comment] 2019-09-09 23:23
If you set "`sccp debug core, channel, callinfo`" the debug logs should be helpfull. I would have to see the before and after though (so the old situation and the new). And please do include some details about the devices and lines taking part in the call. Otherwise it's difficult to figure out what is what (for someone outside your network).
If you can do a `git bisect` that would be most helpfull, as it would show the exact revision that introduced the problem, making it easier to remedy.

**Comment by rofferman** [comment] 2019-09-10 17:18
[sccptosccp.txt](https://github.com/chan-sccp/chan-sccp/files/3596928/sccptosccp.txt)
[sccptosip.txt](https://github.com/chan-sccp/chan-sccp/files/3596931/sccptosip.txt)
 I am attaching the two asterisk logs i captured and am working on getting some other logs.
When i transfer from SCCP to SIP the callerid transfers correctly, it seems only be when i am transferring SCCP to SCCP that it does not. I am using Cisco 7975 and 7942 phones

**Comment by rofferman** [comment] 2019-09-10 17:23
[sccptosccpdegugon.txt](https://github.com/chan-sccp/chan-sccp/files/3596949/sccptosccpdegugon.txt)
Sorry I forgot to have debug on.. Here is the SCCPto SCCP log with debug turned on

Here is the version I am using
Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - ed9fbdbM (built by 'root' on '2019-09-09 15:48:43 UTC')

**Comment by dkgroot** [comment] 2019-09-10 22:02
@rofferman Thanks for the debug logs, but i do need a little more help.

Per debug log, i need to know who is calling who (which phone to which phone). Then which phone is transfering the call, and what the callerid is that you are seeing and what you would have expected.

Example : SIP:A is calling SCCP:B at extension 111. B transfers the call blindly to C using Transfer softkey. When A is connected to B, the correct callinfo is displayed. When the transfer is in progress (RINGING) the incorrect callinfo is displayed on C. etc.

You might have noticed that there are a lot of callerid exchanges happening during a transfer (in the debug log). Also freepbx does some connectedline updates during dialplan handling as well, making this even more difficult (especially for me as an outsider).

Note: FreePBX does alter some of the chan-sccp behaviour regarding callinfo, so i have difficulty reproducing this on vanilla asterisk, that's why i require this extra help. Have you considered using git bisect ?

**Comment by rofferman** [comment] 2019-09-11 22:29
I am calling 812-492-3538 which is the DID for  SCCP phone 3538 from my cell phone. Blind Transferring the call to SIP 3591 using transfer softkey on SCCP phone 3538. when the transfer is in progress it is showing the correct caller id from my cell phone(original incoming call) on SIP 3595. 

I am using the same structure as above to test from SCCP to SCCP. The only difference is that SIP 3591 changes to SCCP 3595. In this scenario the caller id is not transferred from my cell phone. Instead the call transfers to SCCP 3595 but shows SCCP 3538 as the caller

I hope that helps clear it up.. Please let me know if there are any parts I am missing.

I have not used git bisect much but I will look and see if I can find anything with it

**Comment by rofferman** [comment] 2019-09-11 23:53
I have found that this way works, but it used to simpler than this


**If you really want to maintain visibility of the Caller ID, the simplest way we have found is to put the call on hold, grab a line and call the party the call is for, and if they want it, hang up and blind-transfer the call.**

**Comment by anutator** [comment] 2019-10-22 18:36
I also have an issue with softkey - softkey "Answer" during ringing.
When I try to press it nothing happens and I see "this line is not active"
Phone - 7911
softkeyset - [softkey2]
....
ringin=answer,idivert

I pressed two times and could answer only when offhook phone.

[softkey-answer.txt]
(https://github.com/chan-sccp/chan-sccp/files/3757734/softkey-answer.txt)

**Comment by dkgroot** [comment] 2019-10-22 19:19
@rofferman 
> I have found that this way works, but it used to simpler than this
> If you really want to maintain visibility of the Caller ID, the simplest way we have found is to put the call on hold, grab a line and call the party the call is for, and if they want it, hang up and blind-transfer the call.

That does not really sounds like a sensible way of having to do things, i agree. Did your bisect have any result ?

**Comment by dkgroot** [comment] 2019-10-22 19:22
@anutator 
That is completely unrelated to this issue, and could be very confusing (and get lost easily).

Please let's create a new issue for it. Please include some answers to these questions:

Does it only happen on the 7911 Phone. Was this also present in older chan-sccp versions ? Can you show the output of 'Answer' key not working  ( with 'sccp debug core, device, line, channel, softkey, action' set). Does it work correctly with the standard softkeyset ?

**Comment by anutator** [comment] 2019-10-24 15:47
I found info on Cisco forum - Answer key depends on model:

> The determining factor for using the "Answer Softkey" with the Handset On Hook is whether or not the phone model has a speakerphone. If Yes then Answer Softkey is supported, if No (like the 7911,7912,7905) the the Answer Softkey with the Handset On Hook is not supported..You will see that if the Handset is Off-Hook the Answer Softkey is displayed on an Incoming call :) 

Group Pickup button works and I can answer call from my callgroup with button. I'll think. It's not sccp problem as soon as I understand.
Speakerphone is on but there is no microphone. I'd like to answer with softkey even if it doesn't enable microphone and I have to on hook phone after answer but I think it's **impossible by design**.
> The smaller phones are apparently designed to have full handsfree, but the microphone has been removed likely for marketing reasons. The receptacle is on the side and the connector post for the microphone is between the handset and hook switch connector. Somewhere I have a picture of it.

From User Guide:

> Answering a Call
To answer an incoming call, lift up the handset.

> 
> 3.3Using Call Waiting
> If you are enabled with call waiting for your phone, you will hear a call waiting tone and the caller ID information will be shown on the phone’s LCD screen if a new call comes in when you are on the phone.
> 1.To answer the new call, press the Answer soft key. When you do so, the original call will be put on hold.
> 2.To return to the original call, press the Holdbutton.
> 3.If the second call is still active, the call will be put on hold when you return to the original call.
> 4.You can continue to use the Holdbutton to switch between the calls.To create a conference call between yourself and the other two parties, press the Confrn soft key.
> 
> So we press Answer button on 7911 only if we want to answer new call while speaking.

**Comment by dkgroot** [comment] 2019-10-24 16:22
@anutator 

:-)
i never thought about or realised that there were skinny phones without speaker mode. But without a speakermode it makes sense to also suppress the 'answer' softkey. I guess that answers that question. I will have a look at the source code to see if any ajustments should be made to suppress the creation of the Answer SoftKey in this case.

Would you mind create a little entry on our wiki (maybe the frequently asked questions page /  hardware troubleshooting) about this ?

**Comment by rofferman** [comment] 2019-10-28 15:16
I did a bisect and was unable to get to find a working commit
I just got back from vacation and will dig in and try to find some helpdul info in the logs that may point in the right direction.. It is a weird issue.

I did find I think before I left where it is treating the blind transfer as an attended transfer in the debug logs. I tried changing the transfer on hangup option and got the same result.

I will do some more looking and get back. Is there anything you can think of where I should look for more information.

**Comment by dkgroot** [comment] 2019-10-28 20:36
Hope you enjoyed your vacation !
I see you are also using freepbx ? That might explain somethings and might actually help towards a solution as well, if we find out what they are trying to achieve.

`git bisect` also has a `skip` option if/when you end up on a non compiling revision. Also if the compile issue was related to the recent asterisk changes in mwi, i can provide a work around for that (mostly removing some code to disable mwi for the most part during bisecting).

**Comment by rofferman** [comment] 2019-10-30 22:05
I am not sure what happened, maybe a freepbx update but my caller id is transferring now like it should. 
I have not made any changes or pulled any updates from chan sccp, just freepbx and today it is transferring as it should. Very Strange. 
So when a caller calls (A) and the receptionist answers the call (B) when the receptionist pushes the transfer softkey, then presses  the BLF (C) to transfer it to, and hangs up. The original caller id (A) is transferred to pressed BLF line (C).

PS. I hope that made sense. I have been on vacation lol

Just thought I would update

**Comment by dkgroot** [comment] 2019-10-30 22:35
I guess they fixed something upstream which corrected the issue. Chan-sccp and FreePBX do quite a bit of massaging of the callerid information to try and get the right information. I guess we differ in who we think should be responsible for this though :-)

I had already updated the statement above where i said 'enjoy your vacation' after re-reading your previous comment :-)

I guess we can close this issue, right ? Or did i miss something ?

**Comment by tabbertmj** [comment] 2019-10-31 19:08
I'm on FreePBX 14.0.13.6.  I do not see an update listed.  @rofferman, What version are you on?

**Comment by stoyanmarinov** [comment] 2019-11-05 15:50
Had the same issue, dug a bit deeper. The issue is with FreePBX, seems to be fixed in git already about 3 weeks ago. It's an issue with macro-dial-one. If you want to patch yours, go edit /var/www/html/admin/modules/core/functions.inc/macro-dial-one.php

Currently at line 93

replace:
        $ext->add($mcontext,$exten,'', new ext_set('D_OPTIONS', '${D_OPTIONS}I'));
with:
        $ext->add($mcontext,$exten,'', new ext_set('D_OPTIONS', '${D_OPTIONS}'));

(note the missing I, like in uppercase i)

after this rebuild your dialplan (fwconsole reload I guess)

**Comment by dkgroot** [comment] 2019-11-05 16:20
@stoyanmarinov Wow nice find !

**Comment by tabbertmj** [comment] 2019-11-05 16:24
I will give that a try tonight.  Thanks!

**Comment by stoyanmarinov** [comment] 2019-11-05 16:49
Well actually you could just edit the macro-dial-one in extensions_additional.conf. Look for "Set(D_OPTIONS=${D_OPTIONS}I)" and comment out the whole line, then asterisk -x 'dialplan reload'. It's non-disruptive reload of the dialplan, so the only effect would be having properly working blind transfers :)

**Comment by dkgroot** [comment] 2019-12-17 15:53
Closing this issue, as it seems to have been resolve in FreePBX (correct). Please reopen if/when necessary.

**Closed as completed by dkgroot** 2019-12-17 15:53 UTC
Labels: prio 3, branch_development, regression, callinfo, FreePBX
