### ISSUE TITLE
Can't answer incoming call from SIP peer

### ISSUE THREAD

**Issue by CRCinAU** [marcelloceschia/chan-sccp-b#527] opened 2020-08-11 07:06 UTC
When my folks call me from their Cisco SIP phone connected to the same asterisk server, my SCCP phone rings, but when trying to answer, does not answer and continues ringing.

```
voip*CLI> core show version 
Asterisk 16.12.0 built by root @ voip on a x86_64 running Linux on 2020-07-16 17:25:12 UTC
voip*CLI> sccp show version 
Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - 47557d5 (built by 'root' on '2020-08-02 19:57:22 UTC')
voip*CLI> 
```

Attached is the asterisk log with requested debug levels enabled.

There are two SCCP phones in a shared line config, IDs replaced with SEPxxxxxxxxxxxx and SEPyyyyyyyyyyyy.

This log includes:
* Calling from the SIP peer (105) -> SCCP shared line (101)
* Attempting to answer the call via the speaker button - Phone screen shows call timer & solid green line button, but still ringing.
* Hanging up the speaker button when answer fails, phone still ringing.
* Attempt to answer again via the speaker button
* Call terminated from SIP peer's end.

[messages.txt](https://github.com/chan-sccp/chan-sccp/files/5055284/messages.txt)

**Comment by dkgroot** [comment] 2020-08-12 13:57
Hi Steven,
The first thing i notice in the debug output, is that we are talking about huntgroup, not a simple call.
```
Dial("SIP/105-0000000d", "SCCP/101&SIP/102&SIP/103,30,c")
```
Also we seem to be dealing with a shared line as well.

Line 91: `[2020-08-11 06:56:03] ERROR[24215][C-00000003] sccp_channel.c: SCCP/101-0000000F: (sccp_channel_openReceiveChannel) Channel already hanging up` Seems to be the start of the issues.

I have extended the debug logging a little at this location to see what might be the reason. I am suspecting the "Answered Elsewhere" has been set already and we give up. Please try the branch below, so that we get a little bit more insight. From there we should be able to fix this.

***Git***
_Checkout this temporary branch_
```
cd /usr/src/chan-sccp
git fetch origin
git branch issues/527 origin/issues/527
git checkout issues/527
git pull
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
cd /usr/src/chan-sccp
git checkout develop
git pull
./configure [....]
make -j4 && make install && make reload
```

Please show me the new debug out with the same settings and preferably a similar/same call.

**Comment by CRCinAU** [comment] 2020-08-13 06:11
Added log with the same endpoints.

[messages-issues-527.txt](https://github.com/chan-sccp/chan-sccp/files/5067378/messages-issues-527.txt)

**Comment by dkgroot** [comment] 2020-08-13 09:40
As suspected it was the answered_elsewhere check preventing the rtp setup. Pushed an update, please pull latest and retest

**Comment by CRCinAU** [comment] 2020-08-13 11:13
Have done so - will report back tomorrow when I can get my folks to ring that phone...

**Comment by CRCinAU** [comment] 2020-08-14 07:29
Can confirm - this seems to answer calls fine now in that scenario.

**Comment by dkgroot** [comment] 2020-08-14 20:29
Have not merged the change yet, need to check if there would be a regression when/if merged.

**Comment by dkgroot** [comment] 2020-08-15 10:56
Thanks for reporting the issue.
Branch has been merged

**Closed as completed** 2020-08-15 10:55 UTC
Labels: in progress, branch_development, FreePBX
