### ISSUE TITLE
Random end call

### ISSUE THREAD

**Issue by bknv** [marcelloceschia/chan-sccp-b#526] opened 2020-08-05 14:53 UTC
Time to time

, i have problem with phone cisco (7911,7912,7940,7945 and more). Call end random

Find the cause or what is causing the problem - I could not

About my servers:
1)
Virtual Machine on VMware ESXi, 6.5.0, 10884925
Version 6.5
FreePBX 14.0.13.23
Asterisk 13.27.1 built by mockbuild @ jenkins7 on a x86_64 running Linux on 2019-09-06 21:11:59 UTC
Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - 81f140a (built by 'root' on '2020-05-27 18:18:45 UTC')

2)
Virtual Machine on VMware ESXi, 6.5.0, 10884925
Version 6.0
FreePBX 14.0.13.28
Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - 81f140a (built by 'root' on '2020-05-27 18:10:51 UTC')
Asterisk 13.32.0 built by mockbuild @ jenkins7 on a x86_64 running Linux on 2020-03-20 19:19:15 UTC

I want show you example with problem call and corrected. In attach i send next files:  _full.txt
[full.txt](https://github.com/chan-sccp/chan-sccp/files/5029147/full.txt)
_ - log file and _dump.zip_
[dump.zip](https://github.com/chan-sccp/chan-sccp/files/5029168/dump.zip)
 - tcpdump 

Problem call from 2841 to 2840:
Start call - 15:48:41
Answer - 15:48:44
Break(started problem) - 15:48:57
Hangup - 15:49:00

Corrected call from 2841 to 2840:
Start call - 15:49:11
Answer - 15:49:14
Hangup - 15:49:44

P.S. I hope I was able to explain correctly

**Comment by dkgroot** [comment] 2020-08-05 15:07
@bknv
Thanks for reporting the issue. I understand the issue reported.

When i look at the full.txt log, i see INVALIDNUMBER in line 1014. Which seems to be the reason for the failed call. We need to figure out where this is coming from.

Can you make sure that the issue is still present with the latest revision (8f9abc2) ? Also when reporting further debug regarding this problem, we don't need the tcpdump and please set "debug = core, device, line, channel, pbx, action".

**Comment by bknv** [comment] 2020-08-12 06:18
Tommorow i update second server to version 8f9abc2 and will watch for problem

**Comment by dkgroot** [comment] 2020-08-29 16:30
@bknv Have you had any chance to collect some debug log for this issue ?

**Comment by bknv** [comment] 2020-08-31 06:36
At the moment, I have not yet managed to catch this error after updating
Users also did not handle a similar problem
I will definitely report the results

**Comment by dkgroot** [comment] 2020-08-31 10:48
We should close the issue report 1-2 weeks from now, if the issue does not occur anymore.

**Comment by bknv** [comment] 2020-08-31 17:33
I agree with you

**Comment by bknv** [comment] 2020-09-04 09:17
Today user reported me about our problem.
[log.txt](https://github.com/chan-sccp/chan-sccp/files/5173787/log.txt)
Start call 10:42:29
Answer 10:42:32
Break(started problem) 10:42:48


uptime server 3 week 1 day
free -m -w
                     total        used        free      shared     buffers       cache   available
Mem:           3789         940         143         235           0        2705        2270
Swap:          3967         166        3801

**Comment by dkgroot** [comment] 2020-09-04 11:01
Am i right to be checking/tracing this device: SEPA4563041D7FC and call:SCCP/2812-000023F2 on asterisk call thread "C-0000012a" ? Just to make sure before i start looking into it.

**Comment by dkgroot** [comment] 2020-09-04 11:19
(Filtered your log tile using: `grep "C-0000012a" log.txt |grep -v "refcount.c"`)

Looking at this part of the log:
```
[2020-09-04 10:42:33] NOTICE[12370][C-0000012a] sccp_session.c:        > SEPA4563041D7FC: set poll timeout 54 for session 65
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_actions.c:     -- SEPA4563041D7FC: >> Got message Accessory Status Message (0x49)
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_actions.c: SEPA4563041D7FC: SCCP Handle Message: Accessory Status Message(0x0049) 20 bytes length
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_session.c: SEPA4563041D7FC: Sending Message: Clear Notify Message(0x0115) 4 bytes length
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: Clear the display notify message
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: >> Send message Clear Prompt Status Message
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_session.c: SEPA4563041D7FC: Sending Message: Clear Prompt Status Message(0x0113) 12 bytes length
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: Clear the status prompt on line 0 and callid 0
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: ( sccp_device.c:2133:sccp_dev_check_displayprompt ) sccp_dev_displayprompt '' for line 0 (0)
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: >> Send message Display Dynamic Prompt Status Message
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_session.c: SEPA4563041D7FC: Sending Message: Display Dynamic Prompt Status Message(0x0145) 20 bytes length
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_protocol.c:     -- SEPA4563041D7FC: Display prompt on line 0, callid 0, timeout 0
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:     -- SEPA4563041D7FC: softkey 'Redial' on ONHOOK to on
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:        > SEPA4563041D7FC: found softkey 'Redial' at 1
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:     -- SEPA4563041D7FC: softkey 'Confrn' on ONHOOK to on
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:     -- SEPA4563041D7FC: softkey 'Join' on ONHOOK to off
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:     -- SEPA4563041D7FC: softkey 'ConfList' on ONHOOK to on
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_softkeys.c:     -- SEPA4563041D7FC: softkey 'Record' on ONHOOK to off
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: Set softkeyset to ONHOOK(0) on line 0  and call 0
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: validKeyMask 4294967295
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: >> Send message Select SoftKeys Message
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_session.c: SEPA4563041D7FC: Sending Message: Select SoftKeys Message(0x0110) 20 bytes length
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: Finish DisplayPrompt
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_device.c:     -- SEPA4563041D7FC: Accessory 'Handset' is 'On Hook'
```
We can see that the device/phone is sending us :
```
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_actions.c:     -- SEPA4563041D7FC: >> Got message Accessory Status Message (0x49)
[2020-09-04 10:42:48] NOTICE[12370][C-0000012a] sccp_actions.c: SEPA4563041D7FC: SCCP Handle Message: Accessory Status Message(0x0049) 20 bytes length
```
Which translates to `Accessory 'Handset' is 'On Hook'`. And it is coming from the phone the user is using to dial out. The question is did the call break before 10:42:48 (potentialially caused by RTP/audio issue) and did he/she hangup to cancel the connection. Or was the `Accessory 'Handset' is 'On Hook'` message received from the phone an error (problem in the phone firmware ?).

You would have to check ask the user, to make sure if they hungup the call, or it was spontaneously hungup for them. If it was the audio that cut out and everything was still working (except for them hearing anything) we have very different issue to research.

P.S.: Please don't send a log files with sccp log set to all. they are annoying to work through.

**Comment by bknv** [comment] 2020-09-04 12:30
10:42:32 both user joined channel and started RTP. Talk among themselves
after 00:00:12:341 disappear outbound RTP from SCCP/2812
further user SCCP/2817 does not hear abonent SCCP/2812 but there is an outgoing RTP from SCCP/2817

to say for sure whether user 2812 put down the phone at this time (10:42:48) or not - I cannot

sorry if i do something wrong

![image](https://user-images.githubusercontent.com/49523505/92239319-70663000-eec3-11ea-8ecf-3018c27eabec.png)

**Comment by dkgroot** [comment] 2020-09-04 21:06
@bknv Is there a NAT firewall of some kind between the asterisk server and one/both of these phones, that might explain the loss to rtp traffic ?

**Comment by bknv** [comment] 2020-09-07 19:47
NAT - no, these both users locate in one network.
Firewall - yes, but i think if the problem would be with it, both users did not hear each other initially

**Comment by dkgroot** [comment] 2020-09-07 19:51
So there is a firewall between asterisk and/or both phones ? If so the firewall may simply be timing out, causing the interruption in RTP flow. From the information provided it does not look like chan-sccp is actively doing anything to interrupt the call (if it did, it would have logged something, it's pretty chatty as you may have noticed). I think it might be time to look at other potential reasons. As the problem is (seems to be) difficult to reproduce i am not sure how much help i can offer. If it were easier to reproduce i would start with a packet capture.
I am not sure where the nice graph above came from, if that is from an active packet capture, there might be some information in there.

**Comment by bknv** [comment] 2020-09-07 20:05
I can offer the next version:
I can switch off all iptables on server, enable tcpdump and send it when the problem will appear.
What you think about it?

**Comment by dkgroot** [comment] 2020-09-07 21:08
If your server is outward facing (ie: exposed to the internet), then removing all firewallrules might not be such a good idea. If not, and it's safe to do so, then i guess why not. You can start and stop the tcpdump every 15/30 min, after checking there was no incident to safe some room. Having multi megabyte dumps is not a nice thing to have to hunt through.
Note: If something else is causing the incidental drop of rtp packets, i am not sure how much i will be able to do about it. There can be a lot of causes, like switches being overloaded and dropping frames, asterisk rtp issue not forwarding rtp frames, firewalls overflowing and shedding rules etc. Note: chan-sccp is not really part of the RTP handling, and does not have a lot of control over them, once things start flowing.
It might also help to run `rtp set debug on` when an issue is detected/reported, to see if rtp frames are still being relayed. Also the phones might stop sending rtp frames for some reason, and you would have to collect the phones debug log to see if there is any reason it's doing so.
From all of the above, you might understand that this is a complex issue to put a finger on and can be quite hard to get to terms with.

**Comment by bknv** [comment] 2020-09-24 09:16
Hello @dkgroot . 
I disable iptables and problem repeat. 

In 09:44:34 between user 2867(sccp) and 3128(sip) created channel
```
[2020-09-24 09:44:34] VERBOSE[5107][C-000001b3] bridge_channel.c: Channel SIP/3128-000042d6 joined 'simple_bridge' basic-bridge <ac901a40-ce7e-4bb3-8c83-31740d1a1afc>
[2020-09-24 09:44:34] VERBOSE[5032][C-000001b3] bridge_channel.c: Channel SCCP/2867-00004516 joined 'simple_bridge' basic-bridge <ac901a40-ce7e-4bb3-8c83-31740d1a1afc>
```

and both user talk between themselves

in 09:44:36 i see state:INVVALIDNUMBER and next 2867 SCCP device stop all media
```
[2020-09-24 09:44:36] NOTICE[2014][C-0000003f] sccp_indicate.c:     -- SEPF07F06B8DA87: Indicate SCCP new state:INVALIDNUMBER, current channel state:CONNECTED on call:SCCP/2867-00004516, lineInstance:1 (previous channelstate:RINGOUT)
[2020-09-24 09:44:36] NOTICE[2014][C-0000003f] sccp_channel.c:   == SCCP/2867-00004516: (sccp_channel_closeAllMediaTransmitAndReceive) Stop All Media Reception and Transmission on device SEPF07F06B8DA87
```

and 09:44:37 channel left 2867
`[2020-09-24 09:44:37] VERBOSE[5032][C-000001b3] bridge_channel.c: Channel SCCP/2867-00004516 left 'simple_bridge' basic-bridge <ac901a40-ce7e-4bb3-8c83-31740d1a1afc>`

I think that the closure of the rtp happened for a reason state:INVVALIDNUMBER. What you think about it?
May be problem with firmware phone cisco? I Use version SCCP*.9-2-1S
I do not sort the log.txt, so as not to miss anything
[log.txt](https://github.com/chan-sccp/chan-sccp/files/5274771/log.txt)

**Comment by dkgroot** [comment] 2020-09-26 22:34
@bknv I think there might be some issue with one of the schedulers not being cleared, producing the INVALIDNUMBER indication on timeout.

According to the log you provided the scheduled digittimeout should have been cancelled, but it was not 100% clear if this was actually succeeded.
```
[2020-09-24 09:44:20] VERBOSE[12399][C-000001b3] sccp_refcount.c:  sccp_channel.c :1468 (sccp_channel_stop_schedule_digittim) ----->                 refcount increased 05  +> 06 for    channel: SCCP/2867-00004516 (0x7f9918cdccb0)
[2020-09-24 09:44:20] VERBOSE[12399][C-000001b3] sccp_refcount.c:  sccp_channel.c :1468 (sccp_channel_stop_schedule_digittim) <-----                 refcount decreased 05  <- 06 for    channel: SCCP/2867-00004516 (0x7f9918cdccb0)
```
On the first call it ought to have printed: "SCCP/2867-00004516: stop schedule digittimeout XX", but i did not see that. I have added some extra logging in a new branch `issues/526`, to see what is going on exactly.

***Git***
_Checkout this temporary branch_
```
cd /usr/src/chan-sccp
git fetch origin
git branch issues/526 origin/issues/526
git checkout issues/526
git pull
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
cd /usr/src/chan-sccp
git checkout develop
git pull
./configure [....]
make -j4 && make install && make reload
```

**Comment by bknv** [comment] 2020-09-29 06:21
Yesterday i switched to issues/526
I will write when the problem arises

**Comment by bknv** [comment] 2020-10-02 13:44
Sending log

[log.txt](https://github.com/chan-sccp/chan-sccp/files/5318293/log.txt)

**Comment by dkgroot** [comment] 2020-10-03 07:10
@bknv Thanks for the log. I have created a patch that should fix the issue in the current "issues/526" branch. Can you pull it and see if that solves the issue.

**Comment by bknv** [comment] 2020-10-05 09:34
Okey. Today i updating

**Comment by dkgroot** [comment] 2020-10-17 13:44
@bknv Any new results ? Does the new branch fix the issue ?

**Comment by bknv** [comment] 2020-10-19 08:24
Hello, after update (14 day last) we are not see problem. 
In the end of week i suggest to close issue if we will not get problem.

**Comment by dkgroot** [comment] 2020-10-19 08:32
@bknv In that case we should merge the changes. When changes are merged, the issue is automatically closed by the merge. I wlll wait until the end of the week, but it looks like we are pretty confident that the two small changes took care of the issue.

**Comment by bknv** [comment] 2020-10-23 07:57
It's all right. I don't see problem any more

**Comment by dkgroot** [comment] 2020-10-23 13:15
ok mergnig the change ! Thanks for reporting and testing !

**Closed as completed** 2020-11-12 09:16 UTC
Labels: bug, in progress, branch_development, FreePBX
